apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.117.2
    helm:
      values: |
        nameOverride: otel-collector
        fullnameOverride: otel-collector
        mode: daemonset

        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule

        presets:
          logsCollection:
            enabled: false
          hostMetrics:
            enabled: false
          kubernetesAttributes:
            enabled: false
          kubeletMetrics:
            enabled: false
          clusterMetrics:
            enabled: false

        config:
          exporters:
            debug: {}
          extensions:
            health_check:
              endpoint: ${env:MY_POD_IP}:13133
          processors:
            batch: {}
            memory_limiter:
              check_interval: 5s
              limit_percentage: 80
              spike_limit_percentage: 25
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: ${env:MY_POD_IP}:4317
                http:
                  endpoint: ${env:MY_POD_IP}:4318
            prometheus:
              config:
                scrape_configs:
                  - job_name: opentelemetry-collector
                    scrape_interval: 10s
                    static_configs:
                      - targets:
                          - ${env:MY_POD_IP}:8888
          service:
            extensions:
              - health_check
            pipelines:
              logs:
                exporters:
                  - debug
                processors:
                  - memory_limiter
                  - batch
                receivers:
                  - otlp
              metrics:
                exporters:
                  - debug
                processors:
                  - memory_limiter
                  - batch
                receivers:
                  - otlp
                  - prometheus
              traces:
                exporters:
                  - debug
                processors:
                  - memory_limiter
                  - batch
                receivers:
                  - otlp
  destination:
    server: https://kubernetes.default.svc
    namespace: otel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true